# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - APP-RollOfHonour-DEV-UKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          ref: CI/CD-impl

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./RollOfHonour/RollOfHonour.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./RollOfHonour/RollOfHonour.sln --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload Build Artifact for deployment
        uses: actions/upload-artifact@v3.1.2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy_DEV:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'DEV'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'APP-RollOfHonour-DEV-UKS'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_962F9BCB182E48269A190417EFBAC78B }}
          package: .
